/**
 * This file was auto-generated by App Prototyper based on your Supabase schema.
 *
 * These types represent the structure of your Supabase tables.
 *
 * IMPORTANT: When you start fetching data, you'll likely want to create
 * composite types that combine data from related tables. For example,
 * a 'ProductWithImages' type might combine 'Product' and 'ProductImage'.
 */

/**
 * Represents the structure of a JSONB column.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

/**
 * Corresponds to the 'vendors' table.
 */
export interface Vendor {
  id: string; // UUID, PK, FK to auth.users.id
  display_name: string; // TEXT, NOT NULL
  email: string | null; // TEXT, UNIQUE
  avatar_url: string | null; // TEXT
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'stores' table.
 */
export interface Store {
  id: string; // UUID, PK
  vendor_id: string; // UUID, FK to vendors.id, NOT NULL
  name: string; // TEXT, NOT NULL
  description: string; // TEXT, NOT NULL
  logo_url: string | null; // TEXT
  data_ai_hint: string | null; // TEXT
  status: string; // TEXT, NOT NULL (e.g., "active", "pending", "archived")
  category: string; // TEXT, NOT NULL
  location: string | null; // TEXT
  pickup_latitude: number | null;
  pickup_longitude: number | null;
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'social_links' table.
 */
export interface SocialLink {
  id: string; // UUID, PK
  store_id: string; // UUID, FK to stores.id, NOT NULL
  platform: string; // TEXT, NOT NULL (e.g., "twitter", "instagram")
  url: string; // TEXT, NOT NULL
  created_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'products' table.
 * Note: Product images are in the 'ProductImage' table.
 */
export interface Product {
  id: string; // UUID, PK
  store_id: string; // UUID, FK to stores.id, NOT NULL
  name: string; // TEXT, NOT NULL
  category: string; // TEXT, NOT NULL
  price: number; // DECIMAL, NOT NULL
  order_price: number | null; // DECIMAL
  stock: number; // INTEGER, NOT NULL
  status: string; // TEXT, NOT NULL (e.g., "published", "draft", "archived")
  description: string | null; // TEXT
  full_description: string; // TEXT, NOT NULL
  sku: string | null; // TEXT, (store_id, sku) is unique
  tags: string[] | null; // TEXT[]
  weight_kg: number | null; // DECIMAL
  dimensions_cm: Json | null; // JSONB (e.g., { length: number, width: number, height: number })
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'product_images' table.
 */
export interface ProductImage {
  id: string; // UUID, PK
  product_id: string; // UUID, FK to products.id, NOT NULL
  image_url: string; // TEXT, NOT NULL
  data_ai_hint: string | null; // TEXT
  order: number | null; // INTEGER (for display order)
  created_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'customers' table.
 */
export interface Customer {
  id: string; // UUID, PK
  name: string; // TEXT, NOT NULL
  email: string; // TEXT, UNIQUE, NOT NULL
  phone: string | null; // TEXT
  avatar_url: string | null; // TEXT
  data_ai_hint_avatar: string | null; // TEXT
  status: string; // TEXT, NOT NULL (e.g., "active", "inactive")
  tags: string[] | null; // TEXT[]
  street_address: string | null; // TEXT
  city: string | null; // TEXT
  state_province: string | null; // TEXT
  zip_postal_code: string | null; // TEXT
  country: string | null; // TEXT
  joined_date: string | null; // TIMESTAMPTZ
  last_order_date: string | null; // TIMESTAMPTZ
  total_spent: number | null; // DECIMAL
  total_orders: number | null; // INTEGER
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'orders' table.
 */
export interface Order {
  id: string; // UUID, PK
  store_id: string; // UUID, FK to stores.id, NOT NULL
  customer_id: string | null; // UUID, FK to customers.id
  customer_name: string; // TEXT, NOT NULL
  customer_email: string; // TEXT, NOT NULL
  order_date: string; // TIMESTAMPTZ, NOT NULL
  total_amount: number; // DECIMAL, NOT NULL
  delivery_cost: number | null;
  status: string; // TEXT, NOT NULL (e.g., "Pending", "Order Confirmed", "Driver Picking Up", "Delivering", "Delivered", "Cancelled")
  shipping_address: string; // TEXT, NOT NULL
  billing_address: string; // TEXT, NOT NULL
  shipping_method: string | null; // TEXT
  payment_method: string | null; // TEXT
  tracking_number: string | null; // TEXT
  shipping_latitude: number | null;
  shipping_longitude: number | null;
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'order_items' table.
 */
export interface OrderItem {
  id: string; // UUID, PK
  order_id: string; // UUID, FK to orders.id, NOT NULL
  product_id: string; // UUID, FK to products.id, NOT NULL
  product_name_snapshot: string; // TEXT, NOT NULL
  quantity: number; // INTEGER, NOT NULL
  price_per_unit_snapshot: number; // DECIMAL, NOT NULL
  product_image_url_snapshot: string | null; // TEXT
  data_ai_hint_snapshot: string | null; // TEXT
  created_at: string; // TIMESTAMPTZ
}
