/**
 * This file was auto-generated by App Prototyper based on your Supabase schema.
 *
 * These types represent the structure of your Supabase tables.
 *
 * IMPORTANT: When you start fetching data, you'll likely want to create
 * composite types that combine data from related tables. For example,
 * a 'ProductWithImages' type might combine 'Product' and 'ProductImage'.
 */

/**
 * Represents the structure of a JSONB column.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

/**
 * Corresponds to the 'vendors' table.
 */
export interface Vendor {
  id: string; // UUID, PK, FK to auth.users.id
  display_name: string; // TEXT, NOT NULL
  email: string | null; // TEXT, UNIQUE
  avatar_url: string | null; // TEXT
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'stores' table.
 */
export interface Store {
  id: string; // UUID, PK
  vendor_id: string; // UUID, FK to vendors.id, NOT NULL
  name: string; // TEXT, NOT NULL
  description: string; // TEXT, NOT NULL
  logo_url: string | null; // TEXT
  data_ai_hint: string | null; // TEXT
  status: string; // TEXT, NOT NULL (e.g., "active", "pending", "archived")
  categories: string; // TEXT[] but often comes as string or array depending on driver, but SQL says text[]
  location: string | null; // TEXT
  contact_phone: string | null; // TEXT
  contact_email: string | null; // TEXT
  contact_website: string | null; // TEXT
  pickup_latitude: number | null;
  pickup_longitude: number | null;
  settings: Json | null; // JSONB
  banner_url: string | null; // TEXT
  slug: string | null; // TEXT
  is_verified: boolean; // BOOLEAN
  commission_rate: number | null; // NUMERIC
  average_rating: number; // NUMERIC
  review_count: number; // INTEGER
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'social_links' table.
 */
export interface SocialLink {
  id: string; // UUID, PK
  store_id: string; // UUID, FK to stores.id, NOT NULL
  platform: string; // TEXT, NOT NULL (e.g., "twitter", "instagram")
  url: string; // TEXT, NOT NULL
  created_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'products' table.
 * Note: Product images are in the 'ProductImage' table.
 */
export interface Product {
  id: string; // UUID, PK
  store_id: string; // UUID, FK to stores.id, NOT NULL
  name: string; // TEXT, NOT NULL
  category: string; // TEXT, NOT NULL
  price: number; // DECIMAL, NOT NULL
  sale_price: number | null; // DECIMAL
  stock: number; // INTEGER, NOT NULL
  status: string; // TEXT, NOT NULL (e.g., "published", "draft", "archived")
  description: string | null; // TEXT
  full_description: string | null; // TEXT
  sku: string | null; // TEXT, (store_id, sku) is unique
  tags: string[] | null; // TEXT[]
  weight_kg: number | null; // DECIMAL
  dimensions_cm: Json | null; // JSONB
  attributes: Json | null; // JSONB
  search_vector: string | null; // TSVECTOR
  average_rating: number | null; // NUMERIC
  review_count: number | null; // INTEGER
  is_dropshippable: boolean | null; // BOOLEAN
  supplier_product_id: string | null; // UUID
  supplier_price: number | null; // NUMERIC
  order_price: number | null; // NUMERIC
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'product_images' table.
 */
export interface ProductImage {
  id: string; // UUID, PK
  product_id: string; // UUID, FK to products.id, NOT NULL
  image_url: string; // TEXT, NOT NULL
  data_ai_hint: string | null; // TEXT
  order: number | null; // INTEGER (for display order)
  created_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'customers' table.
 */
export interface Customer {
  id: string; // UUID, PK
  name: string; // TEXT, NOT NULL
  email: string; // TEXT, UNIQUE, NOT NULL
  phone: string | null; // TEXT
  status: string; // TEXT, NOT NULL default 'Active'
  tags: string[] | null; // TEXT[]
  avatar_url: string | null; // TEXT
  data_ai_hint_avatar: string | null; // TEXT
  total_spent: number | null; // NUMERIC(10, 2)
  total_orders: number | null; // INTEGER
  joined_date: string | null; // DATE
  last_order_date: string | null; // DATE
  street_address: string | null; // TEXT
  city: string | null; // TEXT
  state_province: string | null; // TEXT
  zip_postal_code: string | null; // TEXT
  country: string | null; // TEXT
  created_at: string | null; // TIMESTAMPTZ
  updated_at: string | null; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'orders' table.
 */
export interface Order {
  id: string; // UUID, PK
  store_id: string; // UUID, FK to stores.id, NOT NULL
  customer_id: string | null; // UUID, FK to customers.id
  customer_name: string; // TEXT, NOT NULL
  customer_email: string; // TEXT, NOT NULL
  order_date: string; // TIMESTAMPTZ, NOT NULL
  total_amount: number; // DECIMAL, NOT NULL
  delivery_cost: number | null;
  status: string; // TEXT, NOT NULL (e.g., "Pending", "Order Confirmed", "Driver Picking Up", "Delivering", "Delivered", "Cancelled")
  shipping_address: string; // TEXT, NOT NULL
  billing_address: string; // TEXT, NOT NULL
  delivery_tier: string | null; // Renamed from shipping_method
  payment_method: string | null; // TEXT
  delivery_code: string | null; // Renamed from tracking_number
  service_fees: number | null; // Added
  escrow_transaction_id: string | null; // Added for Lenco/Escrow integration
  customer_specification: string | null; // TEXT
  shipping_latitude: number | null;
  shipping_longitude: number | null;
  delivery_type: string; // TEXT (e.g., 'courier', 'self_delivery')
  pickup_address: string | null; // TEXT
  pickup_latitude: number | null;
  pickup_longitude: number | null;
  driver_id: string | null; // UUID
  notes: Json | null; // JSONB
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'order_items' table.
 */
export interface OrderItem {
  id: string; // UUID, PK
  order_id: string; // UUID, FK to orders.id, NOT NULL
  product_id: string; // UUID, FK to products.id, NOT NULL
  product_name_snapshot: string; // TEXT, NOT NULL
  quantity: number; // INTEGER, NOT NULL
  price_per_unit_snapshot: number; // DECIMAL, NOT NULL
  product_image_url_snapshot: string | null; // TEXT
  data_ai_hint_snapshot: string | null; // TEXT
  created_at: string; // TIMESTAMPTZ
  cost_per_unit_snapshot: number | null; // NUMERIC
}

/**
 * Corresponds to the 'coupons' table.
 */
export interface Coupon {
  id: string; // UUID, PK
  store_id: string; // UUID, FK to stores.id, NOT NULL
  code: string; // TEXT, NOT NULL
  description: string | null; // TEXT
  discount_type: 'percentage' | 'fixed_amount'; // TEXT check constraint
  discount_value: number; // NUMERIC, NOT NULL
  min_spend: number | null; // NUMERIC
  usage_limit: number | null; // INTEGER
  used_count: number | null; // INTEGER
  start_date: string | null; // TIMESTAMPTZ
  end_date: string | null; // TIMESTAMPTZ
  is_active: boolean | null; // BOOLEAN
  created_at: string | null; // TIMESTAMPTZ
  updated_at: string | null; // TIMESTAMPTZ
}

/**
 * Corresponds to the 'reviews' table.
 */
export interface Review {
  id: string; // UUID, PK
  store_id: string; // UUID, FK
  product_id: string | null; // UUID, FK
  customer_name: string | null; // TEXT
  rating: number; // INTEGER
  comment: string | null; // TEXT
  vendor_reply: string | null; // TEXT
  is_verified_purchase: boolean | null; // BOOLEAN
  created_at: string | null; // TIMESTAMPTZ
  updated_at: string | null; // TIMESTAMPTZ
}
